name: Docs Generation

on:
  push:
    branches:
      - master

jobs:
  GenerateDocs:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout base code
        uses: actions/checkout@v4
        with:
          path: kinference

      - name: Checkout wiki
        uses: actions/checkout@v4
        with:
          repository: ${{github.repository}}.wiki
          path: kinference-wiki

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        working-directory: kinference
        run: |
          python -m pip install -r docs-generator/requirements.txt

      - name: Generate docs
        working-directory: kinference
        run: |
          python docs-generator/main.py --core_doc_file $GITHUB_WORKSPACE/kinference-wiki/KInference-Core-supported-operators.md --tfjs_doc_file $GITHUB_WORKSPACE/kinference-wiki/KInference-TensorFlow.js-supported-operators.md

      - name: Commit updated documentation
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: kinference-wiki
          commit_message: 'CI: Update documentation'
